### ISSUE TITLE
preheader text & intended use

### ISSUE THREAD

**Issue by hnla** [paulgibbs/BuddyPress#10]
I note that the email template describes an element for preheader text (currently having hardcoded placeholder text) and set to 'display: none;'

What is the intention here for this? It is hidden in clients such as Thunderbird but is shown on Android.

It seems that if this is left in ( equally it could be removed as not massively relevant, it is somewhat an email marketers tool) then it would need to be put under the control of the site admin, perhaps a checkbox to enable/disable and selection between message excerpt or user added string?

**Comment by paulgibbs** [comment]
Preheaders indeed only work on some clients. I have seen them in use on emails that I receive and they help me do a quick preview of the email without having to open the email. I kind of like them.

At any rate, I have been contemplating this, and have some of the same thoughts you've thinked.

I am experimenting with pulling the first line from the body of the email content (up to the first line break) to see if it helps/if it is better than the automatic preview such mail clients would otherwise auto-generated themselves.

I had considered adding UI (probably a custom field on the email editor screen) but not convinced the complexity is worth it. Considering having it in the template as a WP action, or supporting a specifically-named Custom Field people could type whatever into. vs. just removing it.

**Comment by hnla** [comment]
> I kind of like them.
Me too, on the whole.

Guess the easiest option always is  to offload the responsibility for them to the user, even if that means a certain amount of additional work, sort of covers all bases.

A custom field in the email CPT editor along with checkbox, could allow the user the choice to add custom string, or leave blank to use first line from the body if checkbox is checked.

As you say though the complexity may not be worth it.

Happy to help test any experimentation.

**Comment by paulgibbs** [comment]
@hnla I've just add an experiment with preheaders in 9869365d8109ff074474ca6737b2cbfddfc54ac0

Edit an email, create a custom field with name `bp_email_preheader`, set a value. Then send yourself an email and test in your favourite preheader-supporting email client.

I'm sort of happy leaving this as an "undocumented" feature, at least in terms of documentation within the UI. We document in the codex, of course, and flag as an advanced feature.

The implementation is pretty flexible so I don't believe we'll have any signficiant backwards compatiblity concerns in the future if we want to change how it works under the hood or if we want to remove it entirely.

**Comment by hnla** [comment]
Just tested.
Think this is a good compromise for first pass. Having the custom field available but not shouting about it seems fine, main thing is those that really think they need it will ask/check codex and find it's easy to achieve. Removing the set custom field returned me to the first few words of body.
