### ISSUE TITLE
Post content body embedded images

### ISSUE THREAD

**Issue by hnla** [paulgibbs/BuddyPress#11]
As it's possible to add images in email post body and as the current email template has a max width any images wider than this max width can overflow the width.

Tested adding max-width & height auto to the emdeded img{} ruleset to prevent this  which seems effective in  desktop and Android.

**Comment by paulgibbs** [comment]
Generally, in this first pass, I am not overly worried about protecting users from themselves in every way possible. If they want to add weird stuff in their Post Editor and find it doesn't work across the majority of their users' email clients, that's not our problem. Extra cotton wool like this make make sense as a v2 in future once we have some real-world feedback on how people are breaking their emails.

Otherwise, quite a lot of email clients...

* ...strip style blocks. For example, gmail web.
* ...don't support `height or `max-width`. For example, Outlook 2007/10/13

Source for above bullets: https://www.campaignmonitor.com/css/

@hnla If you could make a fork/branch with your proposed change in, I'm happy to create an account on https://litmus.com/ and do a before/after test, and share screenshots and we can see 1) if this works 2) and on how many different platforms 3) if it breaks anything else.

**Comment by paulgibbs** [comment]
> Extra cotton wool like this make make sense as a v2 in future once we have some real-world feedback on how people are breaking their emails.

To clarify, by this I meant if it was discovered people kept trying to use certain TinyMCE features etc in emails, we could disable those buttons in a future BP version.

**Comment by hnla** [comment]
Don't mind forking/branching.

The change proposed for this though was  to simply add two properties to embeded styles e.g:

    /* What it does: Uses a better rendering method when resizing images in IE. */
    img {
    -ms-interpolation-mode:bicubic;
    height: auto;
    max-width: 100%;
    }

Even if discarded / ignored by some clients as long as it didn't cause actual issues and did work for some clients to improve the experience, I would tend to add; however this is email formatting and everything needs careful consideration.

This is a minor issue though.

**Comment by paulgibbs** [comment]
OK, if we already have a img block there, let's go for it. It ought to be a pretty minor change.

can you make a PR?

**Comment by hnla** [comment]
It is minor change and can be pulled out without any hassle.

PR sent.

**Comment by paulgibbs** [comment]
Thanks, merged in

(#13)
